/**
 * 파일명: app/component/lang.ko.js
 * 작성자: LSH
 * 갱신일: 2026-05-31
 * 설명: component 경로 한국어 리소스
 */

export const LANG_KO = {
  view: {
    mobileTitle: "컴포넌트 문서",
    openTocAriaLabel: "목차 열기",
    openTocLabel: "목차",
    closeTocAriaLabel: "목차 닫기",
    tocLabel: "목차",
    closeLabel: "닫기",
    descriptionHeading: "설명",
    scrollTopAriaLabel: "맨 위로 이동",
    copyDoneLabel: "복사됨!",
    tocLabels: {
      dataclass: "1. 데이터 클래스 (Data Class)",
      dataclassEasyObj: "- EasyObj",
      dataclassEasyList: "- EasyList",
      buttons: "2. 버튼 (Button)",
      buttonVariants: "- 버튼 종류",
      buttonSizes: "- 버튼 크기",
      icons: "3. 아이콘 (Icon)",
      iconBasic: "- 기본 사용",
      inputs: "4. 입력 (Input)",
      inputBasic: "- 기본 입력",
      inputMask: "- 마스킹 입력",
      inputFilter: "- 필터 입력",
      inputAdvanced: "- 고급 입력",
      textareas: "5. 멀티라인 입력 (Textarea)",
      textareaBasic: "- 기본",
      textareaStates: "- 상태",
      selects: "6. 선택 (Select)",
      selectBasic: "- 기본 사용",
      selectStates: "- 상태",
      checkboxes: "7. 체크박스 (Checkbox)",
      checkboxBasic: "- 기본 사용",
      checkboxVariants: "- 변형",
      checkbuttons: "8. 체크버튼 (CheckButton)",
      checkbuttonBasic: "- 기본 사용",
      checkbuttonVariants: "- 변형",
      radioboxes: "9. 라디오박스 (Radiobox)",
      radioboxBasic: "- 기본 사용",
      radioboxVariants: "- 변형",
      radiobuttons: "10. 라디오버튼 (RadioButton)",
      radiobuttonBasic: "- 기본 사용",
      radiobuttonVariants: "- 변형",
      switches: "11. 스위치 (Switch)",
      switchBasic: "- 기본 사용",
      switchStates: "- 상태",
      numberInputs: "12. 숫자 입력 (NumberInput)",
      numberBasic: "- 기본",
      numberRange: "- 범위",
      numberUnbound: "- 언바운드",
      datetimeInputs: "13. 날짜/시간 (Date/Time)",
      dateBasic: "- 날짜 기본",
      timeBasic: "- 시간 기본",
      comboboxes: "14. 콤보박스 (Combobox)",
      comboboxBasic: "- 기본",
      comboboxBound: "- 바운드",
      comboboxMulti: "- 멀티",
      dropdowns: "15. 드롭다운 (Dropdown)",
      dropdownBasic: "- 기본",
      dropdownStyles: "- 스타일",
      loading: "16. 로딩 (Loading)",
      loadingBasic: "- 기본 사용",
      alerts: "17. 알림 (Alert)",
      alertBasic: "- 기본",
      alertTypes: "- 유형",
      confirms: "18. 확인 (Confirm)",
      confirmBasic: "- 기본",
      toasts: "19. 토스트 (Toast)",
      toastBasic: "- 기본",
      tooltips: "20. 툴팁 (Tooltip)",
      tooltipBasic: "- 기본",
      tooltipPlacement: "- 위치",
      badges: "21. 배지 (Badge)",
      badgeBasic: "- 기본",
      badgeVariants: "- 변형",
      stats: "22. 통계 (Stat)",
      statBasic: "- 기본",
      skeletons: "23. 스켈레톤 (Skeleton)",
      skeletonText: "- 텍스트",
      skeletonCard: "- 카드",
      empties: "24. 빈 상태 (Empty)",
      emptyBasic: "- 기본",
      emptyAction: "- 액션",
      cards: "25. 카드 (Card)",
      cardBasic: "- 기본",
      cardLayouts: "- 레이아웃",
      tables: "26. 테이블 (Table)",
      tableBasic: "- 기본",
      tableControlled: "- 컨트롤드",
      pagination: "27. 페이지네이션 (Pagination)",
      paginationBasic: "- 기본",
      paginationAdvanced: "- 고급",
      tabs: "28. 탭 (Tab)",
      tabBasic: "- 기본",
      tabVariants: "- 변형",
      drawers: "29. 드로어 (Drawer)",
      drawerRight: "- 오른쪽",
      drawerLeft: "- 왼쪽",
      modals: "30. 모달 (Modal)",
      modalBasic: "- 기본",
      modalSizes: "- 크기",
      editors: "31. 리치 에디터 (EasyEditor)",
      editorBasic: "- 기본",
      editorBound: "- 바운드",
      easychart: "32. 차트 (EasyChart)",
      easychartLine: "- 라인",
      easychartBar: "- 바",
      pdfviewer: "33. PDF 뷰어 (PdfViewer)",
      pdfBasic: "- 기본",
      pdfRemote: "- 원격",
    },
  },
};

export default LANG_KO;
